/**
 * TipJar Client (Stub)
 * 
 * NOTE: This is a stub file generated to allow TypeScript compilation.
 * The actual client will be generated by algokit when the smart contract
 * compilation succeeds.
 * 
 * To generate the real client:
 * 1. Ensure algokit and puya-ts are properly installed
 * 2. Run: npm run build
 * 3. This stub will be replaced with the actual generated client
 */

export interface DeployResult {
  appClient: {
    appClient: {
      appId: number
    }
    appAddress: string
    send: any
  }
  result: {
    operationPerformed: 'create' | 'replace' | 'update'
  }
}

export class TipJarFactory {
  constructor(config: any) {
    // Stub implementation
  }

  async deploy(options: any): Promise<DeployResult> {
    throw new Error('TipJar smart contract client not yet generated. Run: npm run build')
  }
}

export default TipJarFactory
